CREATE TABLE SystemUser (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    username VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL
    );

CREATE TABLE ITEM(
    ID INT PRIMARY KEY NOT NULL,
    NAME VARCHAR(500),
    TEXTDESCTIPTION TEXT,
    PHOTO VARCHAR(500),
    SYSTEMUSER_ID INT REFERENCES ITEM(ID)
);

CREATE TABLE HISTORY (
    ID SERIAL PRIMARY KEY 
);

CREATE TABLE TRADECACHE (
    ID INT PRIMARY KEY NOT NULL ,
    SENDER_ID INT  REFERENCES SYSTEMUSER(ID),
    RECIVER_ID INT REFERENCES SYSTEMUSER(ID),
    SENDERITEMS_ID INT   REFERENCES ITEM(ID),
    RECIVERITEMS_ID INT REFERENCES ITEM(ID)
);
